version: "3.9"
services:
  user_ms_service:
    build:
      dockerfile: Dockerfile.test
      context: .
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "root"
        ]
      timeout: 20s
      interval: 10s
      retries: 3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=wrs
      - APP_DB_PASS=qwerty
      - APP_DB_NAME=wrs_user_ms
      - APP_DB_FOR_TESTS_NAME=wrs_user_ms_test
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  migrate_test:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://wrs:qwerty@db:5432/wrs_user_ms_test?sslmode=disable",
        "up"
      ]
    links:
      - db
    depends_on:
      - db
    restart: on-failure

volumes:
  db:
    driver: local

networks:
  default:
    name: wrsnet
