version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
    command: run
    ports:
      - "50051:50051"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - '127.0.0.1:35006:6379'
    volumes:
      - redis:/var/lib/redis
    restart: unless-stopped

volumes:
  redis:
    driver: local

networks:
  default:
    name: wrsnet
