[services]

[services.server]
PORT = 50051

[services.database]
DB_URL = "postgres://wrs:qwerty@db:5432/wrs_user_ms?sslmode=disable"
DB_URL_TEST = "postgres://wrs:qwerty@db:5432/wrs_user_ms_test?sslmode=disable"

[services.redis]
HOST = "localhost"
PORT = 6379
DB = 1

